### ISSUE TITLE
Conflict Between Optimole v4.0+ and WP Show Posts Plugin

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#926]
### Description

After updating to **Optimole v4.0 or later**, a conflict occurs with the **[WP Show Posts](https://wordpress.org/plugins/wp-show-posts/)** plugin.  
When using WP Show Posts to display a listing, if the image `width` and `height` attributes are set, the listing images appear broken on the frontend. The `src` attribute does not contain any image URL.

This issue does not occur with **Optimole v3.14.1**, where the integration works correctly without any problems.

Issue URL - https://varioustrip.s4-tastewp.com/wp-show-posts-issue/

### Additional Notes
- The issue specifically occurs when custom width and height attributes are manually added.
- Tested on a clean WordPress installation with only Optimole and WP Show Posts activated.
- No errors were observed in the console; only broken images on the frontend.

### Step-by-step reproduction instructions

1. Install the latest versions of **Optimole** and **WP Show Posts** plugins.
2. Create a few posts with featured images.
3. Create a listing in WP Show Posts and configure custom image `width` and `height` attributes.
4. Copy the listing shortcode and add it to a page or post.
5. View the page — the images will appear broken.
6. Roll back Optimole to **v3.14.1** — the images will display correctly without issues.

### Screenshots, screen recording, code snippet or Help Scout ticket

Reported by: https://secure.helpscout.net/conversation/2917512045/462870
```

URL: https://varioustrip.s4-tastewp.com
Username: kushnamdev
Password: ZCjNHurJQLk

```

<img width="1257" alt="Image" src="https://github.com/user-attachments/assets/a8ecb6fc-b7ba-4066-b1ea-139ef5380c92" />
<img width="1198" alt="Image" src="https://github.com/user-attachments/assets/392e5c43-009e-428c-9542-c251ae7b882c" />

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by selul** [comment]
@kushh23 I've tried to fix this here https://github.com/Codeinwp/optimole-wp/pull/927, can you have a look? 

I've reported also the issue to the plugin owner here https://github.com/tomusborne/wp-show-posts/issues/50

We fixed a bug in the most recent version which triggered this. The problem was previously present too but only in the context when the images were offloaded.

**Comment by kushh23** [comment]
@selul Following up on the previous findings — the user confirmed that the issue is still unresolved on their end.

After further investigation, we found that the problem occurs when using the adverts post type from the [WP Adverts](https://wordpress.org/plugins/wpadverts/) plugin. When this post type is used in conjunction with WP Show Posts, the image placeholders fail to load correctly.

### Test Site Details:
```
Issue page: https://historicalmuscle.s4-tastewp.com/issue-page/
Optimole disabled version: https://historicalmuscle.s4-tastewp.com/issue-page/?optml_off=true
URL: https://historicalmuscle.s4-tastewp.com/
Username: kushnamdev
Password: _xTXIko7G4o
```

### Steps to Reproduce:

1. Install the latest versions of Optimole, [WP Adverts](https://wordpress.org/plugins/wpadverts/), and [WP Show Posts ](https://wordpress.org/plugins/wp-show-posts/)plugins.
2. Create a new post under the Adverts post type and upload images.
3. In WP Show Posts, create a new listing:
 - Set the post type to adverts.
 - Define custom image width and height attributes.
4. Insert the listing shortcode into a page or post.
5. View the page — the image placeholders will not load.

Screenshots:

![Image](https://github.com/user-attachments/assets/c26e9f8e-34f6-4806-9b3a-d3b18c54e9d4)

Let me know if you need any additional details to escalate this further.

**Comment by selul** [comment]
@kushh23 this is not a bug from Optimole, wp adverts is not showing the thumbnail when we are in a loop of adverts, see the code https://github.com/simpliko/wpadverts/blob/e383af75b1b30c0a6379c81e81baa92c57e711f7/includes/functions.php#L547

If the user wants to show this, he can remove their filter, by using: 
```php
remove_filter('post_thumbnail_html', 'adverts_post_thumbnail_html');
```

Is nothing that we can fix from our end. 

The reason why was working before was due to a bug in the plugin like I've mentioned.

**Comment by kushh23** [comment]
Thank you so much for investigating this.
